### ISSUE TITLE
I got this when I tried to run the Windows installer

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [FantasyInternet/cyberterminal#6]
![bandicam 2018-06-22 19-08-56-107](https://user-images.githubusercontent.com/30059831/41806001-d2780320-7668-11e8-8ef8-ac2160fdc946.jpg)

Likely an overuse of 4GB RAM? The web version of Cyberterminal works fine especially with 32-bit. This is the fourth fantasy thing I'm aware of that is officially compiled for only 64-bit platforms. Though I think the idea of virtual internet is nice, this could've also been an add-on to existing fantasy consoles/computers.

**Comment by codeartisticninja** [comment]
I was not aware that the installer doesn't work on 32-bit Windows.. I will look into that..

**Comment by codeartisticninja** [comment]
The lastest version of the Windows installer should now work on 32-bit.. can you confirm..?
https://github.com/FantasyInternet/cyberterminal/releases/tag/v0.2

**Comment by The-Beesh-Spweesh** [comment]
It worked all the way through!

**Comment by codeartisticninja** [comment]
Great :)
